Add all gsocstest changes (squashed)

diff --git a/external/bsd/openresolv/dist/resolvconf.in b/external/bsd/openresolv/dist/resolvconf.in
--- a/external/bsd/openresolv/dist/resolvconf.in
+++ b/external/bsd/openresolv/dist/resolvconf.in
@@ -25,7 +25,7 @@
 # OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
 RESOLVCONF="$0"
-OPENRESOLV_VERSION="3.16.3"
+OPENRESOLV_VERSION="3.17.4"
 SYSCONFDIR=@SYSCONFDIR@
 LIBEXECDIR=@LIBEXECDIR@
 VARDIR=@VARDIR@
@@ -104,12 +104,12 @@ fi
 
 warn()
 {
-	echo "$@" >&2
+	echo "${RESOLVCONF##*/}: $*" >&2
 }
 
 error_exit()
 {
-	echo "$@" >&2
+	warn "$*"
 	exit 1
 }
 
@@ -233,8 +233,34 @@ exclusive_key()
 	return 1
 }
 
+# Quote input so it can be safely used for variable assignment via eval
+quote()
+{
+	if [ -z "$1" ]; then
+		R="''"
+	else
+		R=
+		for W; do
+			while [ -n "$W" ]; do
+				case "$W" in
+				\'*)  R="$R\\'"; W=${W#?};;
+				?\'*) R="$R\\${W%%\'*}"; W="${W#?}";;
+				*\'*) R="$R'${W%%\'*}'"; W="'${W#*\'}";;
+				?)    R="$R\\$W"; W=;;
+				*)    R="$R'$W'"; W=;;
+				esac
+			done
+		done
+	fi
+
+	printf '%s\n' "$R"
+	return 0
+}
+
 # Parse resolv.conf's and make variables
 # for domain name servers, search name servers and global nameservers
+# Important! Each printf here should use the above quote function
+# to ensure that user input is quoted for eval.
 parse_resolv()
 {
 	domain=
@@ -275,7 +301,7 @@ parse_resolv()
 				esac
 			done
 			if $islocal; then
-				echo "LOCALNAMESERVERS=\"\$LOCALNAMESERVERS $value\""
+				printf 'LOCALNAMESERVERS="$LOCALNAMESERVERS "%s\n' "$(quote "$value")"
 			else
 				ns="$ns${ns:+ }$value"
 			fi
@@ -285,7 +311,7 @@ parse_resolv()
 			if [ -z "$domain" ]; then
 				domain="$search"
 				if ! $nosearch; then
-					echo "DOMAIN=\"$domain\""
+					printf 'DOMAIN=%s\n' "$(quote "$domain")"
 				fi
 			fi
 			;;
@@ -303,13 +329,13 @@ parse_resolv()
 				for d in $search; do
 					ds="$ds${ds:+ }$d:$newns"
 				done
-				echo "DOMAINS=\"\$DOMAINS $ds\""
+				printf 'DOMAINS="$DOMAINS "%s\n' "$(quote "$ds")"
 			fi
 			if ! $nosearch; then
-				echo "SEARCH=\"\$SEARCH $search\""
+				printf 'SEARCH="$SEARCH "%s\n' "$(quote "$search")"
 			fi
 			if ! $private; then
-				echo "NAMESERVERS=\"\$NAMESERVERS $ns\""
+				printf 'NAMESERVERS="$NAMESERVERS "%s\n' "$(quote "$ns")"
 			fi
 			ns=
 			search=
@@ -336,7 +362,7 @@ dirname()
 {
 	OIFS="$IFS"
 	IFS=/
-	set -- "$@"
+	set -- $@
 	IFS="$OIFS"
 	if [ -n "$1" ]; then
 		printf %s .
@@ -569,7 +595,7 @@ list_keys() {
 	if [ "$list_cmd" = -i ] || [ "$list_cmd" = -l ]; then
 		for i in $@; do
 			if [ ! -f "$i" ]; then
-				if ! $force; then
+				if ! $force && [ "$i" != "*" ]; then
 					echo "No resolv.conf for key $i" >&2
 				fi
 				retval=2
@@ -1004,6 +1030,7 @@ make_vars()
 			newdomains="$newdomains${newdomains:+ }$dn:$newns"
 		fi
 	done
+
 	DOMAIN="$(list_remove domain_blacklist $DOMAIN)"
 	SEARCH="$(uniqify $SEARCH)"
 	SEARCH="$(list_remove domain_blacklist $SEARCH)"
@@ -1011,11 +1038,13 @@ make_vars()
 	NAMESERVERS="$(list_remove name_server_blacklist $NAMESERVERS)"
 	LOCALNAMESERVERS="$(uniqify $LOCALNAMESERVERS)"
 	LOCALNAMESERVERS="$(list_remove name_server_blacklist $LOCALNAMESERVERS)"
-	echo "DOMAIN='$DOMAIN'"
-	echo "SEARCH='$SEARCH'"
-	echo "NAMESERVERS='$NAMESERVERS'"
-	echo "LOCALNAMESERVERS='$LOCALNAMESERVERS'"
-	echo "DOMAINS='$newdomains'"
+
+	# Ensure output is quoted for eval
+	printf 'DOMAIN=%s\n' "$(quote "$DOMAIN")"
+	printf 'SEARCH=%s\n' "$(quote "$SEARCH")"
+	printf 'NAMESERVERS=%s\n' "$(quote "$NAMESERVERS")"
+	printf 'LOCALNAMESERVERS=%s\n' "$(quote "$LOCALNAMESERVERS")"
+	printf 'DOMAINS=%s\n' "$(quote "$newdomains")"
 }
 
 force=false
@@ -1054,19 +1083,11 @@ if [ -n "$key" ]; then
 fi
 
 if [ -z "$cmd" ]; then
-       	if [ "$IF_PRIVATE" = 1 ]; then
+	if [ "$IF_PRIVATE" = 1 ]; then
 		cmd=p
 	elif [ "$IF_EXCLUSIVE" = 1 ]; then
 		cmd=x
 	fi
-fi
-
-# -I inits the state dir
-if [ "$cmd" = I ]; then
-	if [ -d "$VARDIR" ]; then
-		rm -rf "$VARDIR"/*
-	fi
-	exit $?
 fi
 
 # -D ensures that the listed config file base dirs exist
@@ -1135,7 +1156,7 @@ a|d|C|c)
 		error_exit "Key not specified"
 	fi
 	;;
-u)	;;
+I|u)	;;
 *)
 	if [ -n "$cmd" ] && [ "$cmd" != h ]; then
 		error_exit "Unknown option $cmd"
@@ -1145,14 +1166,14 @@ u)	;;
 esac
 
 if [ "$cmd" = a ]; then
-	for x in '/' \\ ' ' '*'; do
-		case "$iface" in
-		*[$x]*) error_exit "$x not allowed in key name";;
+	for x in '/' '\' ' ' '*'; do
+		case "$key" in
+		"$x"|"$x"*|*"$x"|*"$x"*) error_exit "$x not allowed in key name";;
 		esac
 	done
 	for x in '.' '-' '~'; do
-		case "$iface" in
-		[$x]*) error_exit \
+		case "$key" in
+		"$x"*) error_exit \
 			"$x not allowed at start of key name";;
 		esac
 	done
@@ -1364,7 +1385,7 @@ a)
 
 	if $changedfile; then
 		printf "%s\n" "$resolv" >"$KEYDIR/$key" || exit $?
-	elif ! $changed; then
+	elif ! $changed && [ ! -e "$VARDIR"/error ]; then
 		exit 0
 	fi
 	unset changed changedfile oldmetric newmetric x oldexcl
@@ -1385,7 +1406,7 @@ d)
 			"$EXCLUSIVEDIR/"*" $i" || exit $?
 	done
 
-	if ! $changed; then
+	if ! $changed && [ ! -e "$VARDIR"/error ]; then
 		# Set the return code based on the forced flag
 		$force
 		exit $?
@@ -1404,7 +1425,9 @@ C)
 			echo " " >"$i" || exit $?
 		fi
 	done
-	$changed || exit 0
+	if ! $changed && [ ! -e "$VARDIR"/error ]; then
+		exit 0
+	fi
 	unset changed i
 	;;
 
@@ -1419,9 +1442,21 @@ c)
 				rm "$i" || exit $?
 			fi
 		done
-		$changed || exit 0
+		if ! $changed && [ ! -e "$VARDIR"/error ]; then
+			exit 0
+		fi
 		unset changed i
 	fi
+	;;
+I)
+	# Init the state dir, keeping our lock and key directories only
+	for i in "$VARDIR"/*; do
+		case "$i" in
+			"$LOCKDIR") ;;
+			"$KEYDIR") rm -rf "$KEYDIR"/*;;
+			*) rm -rf "$i";;
+		esac
+	done
 	;;
 esac
 
@@ -1461,5 +1496,9 @@ for script in "$LIBEXECDIR"/*; do
 		retval=$(($retval + $?))
 	fi
 done
+if [ "$retval" = 0 ]; then
+	rm -f "$VARDIR"/error
+else
+	echo "$retval" >"$VARDIR"/error
+fi
 exit $retval
-
